import {chartPath} from './data.js?v=20';
import {chartCoordinate} from './ui.js?v=20';

export function dexEmbedURL(pair,theme='dark') {
 if(!/^[a-z0-9-]+$/i.test(pair.chain||'')||!/^[a-z0-9]+$/i.test(pair.address||''))return null;
 const url=new URL(`https://dexscreener.com/${pair.chain}/${pair.address}`);
 url.search=new URLSearchParams({embed:'1',loadChartSettings:'0',info:'0',chartLeftToolbar:'0',chartDefaultOnMobile:'1',chartTheme:theme==='light'?'light':'dark',theme:theme==='light'?'light':'dark',chartStyle:'0',chartType:'usd',interval:'15'}).toString();
 return url.href;
}

export function sentimentOverview(data,{e,num,date,link}) {
 const labels={'Extreme Fear':'ترس شدید',Fear:'ترس',Neutral:'خنثی',Greed:'طمع','Extreme Greed':'طمع شدید'};
 const first=data.items[0], angle=-180+first.value*1.8;
 const find=days=>data.items.find(x=>Math.abs(Date.parse(x.time)-(Date.parse(first.time)-days*86400000))<3600000);
 return `<div class="sentiment-overview"><section class="panel"><h2>شاخص ترس و طمع</h2><svg class="sentiment-gauge" viewBox="0 0 240 160" role="img" aria-label="شاخص ${num(first.value)} از ${num(100)}؛ ${e(labels[first.classification]||first.classification)}"><path d="M30 125 A90 90 0 0 1 210 125" fill="none" stroke="var(--border)" stroke-width="18"/><path d="M30 125 A90 90 0 0 1 210 125" pathLength="100" fill="none" stroke="var(--accent)" stroke-width="18" stroke-dasharray="${first.value} 100"/><line x1="120" y1="125" x2="198" y2="125" transform="rotate(${angle} 120 125)" stroke="var(--text)" stroke-width="4"/><circle cx="120" cy="125" r="7" fill="var(--text)"/><text x="22" y="153" fill="var(--muted)" font-size="12">0</text><text x="197" y="153" fill="var(--muted)" font-size="12">100</text></svg><p class="gauge-value">${num(first.value)} <span>${e(labels[first.classification]||first.classification)}</span></p>${link(data.source_url,'منبع: Alternative.me')}<p class="muted">زمان شاخص: ${e(date(first.time))}</p></section><section class="panel"><h2>مقایسه زمانی</h2>${[[0,'اکنون'],[1,'دیروز'],[7,'هفته قبل'],[30,'۳۰ روز قبل']].map(([days,label])=>{const p=find(days);return `<div class="sentiment-comparison"><div>${label}<small>${p?e(labels[p.classification]||p.classification):'در دسترس نیست'}</small></div><strong>${p?num(p.value):'—'}</strong></div>`;}).join('')}</section><section class="panel"><h2>به‌روزرسانی بعدی منبع</h2><p class="gauge-value">${data.next_update?e(date(data.next_update)):'زمان اعلام نشده'}</p><p class="muted">زمان اعلام‌شده توسط منبع؛ دریافت سایت هر ۶ ساعت انجام می‌شود.</p><p class="hint">شاخص عمدتاً مربوط به بیت‌کوین است و سیگنال خرید یا فروش نیست.</p></section></div>`;
}

function plot(points,title,{e,money,date}) {
 if(!points.length)return '<p class="empty">داده این معیار موجود نیست.</p>';
 const min=Math.min(...points.map(p=>p.price)),max=Math.max(...points.map(p=>p.price));
 return `<div class="price-plot"><div class="price-axis" aria-hidden="true">${[1,.75,.5,.25,0].map(t=>`<span>${money(min+(max-min)*t,true)}</span>`).join('')}</div><svg class="chart" preserveAspectRatio="none" viewBox="0 0 900 250" role="img" aria-label="${e(title)}؛ مقادیر در جدول زیر">${[12,68.5,125,181.5,238].map(y=>`<line x1="12" x2="888" y1="${y}" y2="${y}" stroke="var(--border)" stroke-dasharray="4 6"/>`).join('')}<path d="${chartPath(points)}" fill="none" stroke="var(--accent)" stroke-width="3" vector-effect="non-scaling-stroke"/><circle id="protocol-marker" r="5" fill="var(--accent)"/></svg></div><div class="chart-times" dir="ltr"><span>${e(date(points[0].time))}</span><span>${e(date(points.at(-1).time))}</span></div><div class="chart-inspector"><label for="protocol-point">بررسی نقطه نمودار با کلیدهای جهت‌نما</label><input id="protocol-point" type="range" min="0" max="${points.length-1}" value="${points.length-1}" dir="ltr"><output id="protocol-value"></output></div><details><summary>جدول داده‌های نمودار</summary><div class="explore-table"><table><thead><tr><th>زمان</th><th>USD</th></tr></thead><tbody>${points.map(p=>`<tr><td>${e(date(p.time))}</td><td>${money(p.price)}</td></tr>`).join('')}</tbody></table></div></details>`;
}

export async function renderProtocolBrowser(container,ctx) {
 const {client,current,e,num,money,date,link}=ctx;
 let request=0;
 container.innerHTML='<div class="analytics-controls"><div><label for="protocol-select">پروتکل تحلیلی</label><select id="protocol-select"><option value="lido">Lido</option><option value="aave">Aave</option><option value="uniswap">Uniswap</option></select></div><div><label for="protocol-metric">معیار نمودار</label><select id="protocol-metric"><option value="tvl">TVL</option><option value="dailyFees">کارمزد روزانه</option><option value="dailyRevenue">درآمد روزانه پروتکل</option></select></div><div><label for="protocol-range">بازه</label><select id="protocol-range"><option value="30">۳۰ روز</option><option value="365">۱ سال</option><option value="all">کل تاریخچه</option></select></div></div><div id="protocol-body"></div>';
 const body=container.querySelector('#protocol-body'),select=container.querySelector('#protocol-select'),metric=container.querySelector('#protocol-metric'),range=container.querySelector('#protocol-range');
 let data;
 const draw=()=>{
  const p=data?.items?.[0];if(!p){body.innerHTML='<p class="empty">داده این پروتکل هنوز آماده نیست.</p>';return;}
  const raw=metric.value==='tvl'?p.history:p.metrics[metric.value]?.points||[];
  const points=range.value==='all'?raw:raw.filter(x=>Date.parse(x.time)>=Date.parse(raw.at(-1)?.time)-Number(range.value)*86400000);
  const stat=(title,value)=>`<div class="data-card"><small class="muted">${title}</small><strong>${value===null||value===undefined?'در دسترس نیست':money(value,true)}</strong></div>`;
  body.innerHTML=`<div class="heading"><h2>${e(p.name)} <bdi class="muted">${e(p.symbol||'')}</bdi></h2>${link(data.source_url,'DefiLlama')}</div><p class="muted">دریافت: ${e(date(data.fetched_at))}${data.freshness==='stale'?' · داده قدیمی':''}${data._offline?' · آفلاین':''}</p><div class="protocol-stats">${stat('آخرین TVL',p.history.at(-1)?.price)}${stat('کارمزد ۲۴ ساعت',p.metrics.dailyFees?.total_24h)}${stat('درآمد پروتکل ۲۴ ساعت',p.metrics.dailyRevenue?.total_24h)}${stat('کارمزد ۳۰ روز',p.metrics.dailyFees?.total_30d)}${stat('درآمد پروتکل ۳۰ روز',p.metrics.dailyRevenue?.total_30d)}</div><h3>${e(metric.selectedOptions[0].textContent)} · USD</h3>${plot(points,metric.selectedOptions[0].textContent,ctx)}<p class="hint">کارمزد پرداختی کاربران با درآمد پروتکل متفاوت است. بازه نسبت به آخرین نقطه موجود در منبع محاسبه می‌شود.</p><details><summary>درباره پروتکل و روش محاسبه منبع</summary><p dir="auto">${e(p.description||'')}</p><p dir="auto">${e(p.metrics[metric.value]?.methodology||'روش محاسبه را در صفحه منبع بررسی کنید.')}</p></details>`;
  const slider=body.querySelector('#protocol-point');if(slider){const update=()=>{const i=Number(slider.value),point=points[i],xy=chartCoordinate(points,i);body.querySelector('#protocol-value').textContent=`${date(point.time)} · ${money(point.price).replace(/<[^>]+>/g,'')}`;slider.setAttribute('aria-valuetext',`${date(point.time)}؛ ${point.price} USD`);const dot=body.querySelector('#protocol-marker');dot.setAttribute('cx',xy.x);dot.setAttribute('cy',xy.y);};slider.addEventListener('input',update);update();}
 };
 const load=async()=>{const id=++request;body.innerHTML='<p role="status">در حال دریافت تاریخچه پروتکل…</p>';try{const result=await client.get('/api/v1/protocols/'+select.value);if(id!==request||!current())return;data=result;draw();}catch{if(id===request&&current())body.innerHTML='<p class="error">دریافت اطلاعات پروتکل ناموفق بود.</p><button id="protocol-retry">تلاش دوباره</button>';body.querySelector('#protocol-retry')?.addEventListener('click',load);}};
 select.addEventListener('change',load);metric.addEventListener('change',draw);range.addEventListener('change',draw);await load();
}

export function dexDetails(p,{e,num,money,date,link},period='h24') {
 const value=p.periods?.[period]||{},buys=value.buys,sells=value.sells,change=value.change;
 const metric=(label,v)=>`<div class="data-card"><small>${label}</small><strong>${v}</strong></div>`;
 return `<nav class="analytics-controls" aria-label="بازه آمار جفت">${Object.entries({m5:'۵ دقیقه',h1:'۱ ساعت',h6:'۶ ساعت',h24:'۲۴ ساعت'}).map(([k,v])=>`<button data-dex-period="${k}" aria-pressed="${k===period}">${v}</button>`).join('')}</nav><div class="protocol-stats">${metric('تغییر قیمت',change===null||change===undefined?'—':`<bdi class="${change<0?'negative':'positive'}">${change>0?'+':''}${num(change)}%</bdi>`)}${metric('حجم این بازه',money(value.volume,true))}${metric('تعداد خرید',buys===null||buys===undefined?'—':num(buys))}${metric('تعداد فروش',sells===null||sells===undefined?'—':num(sells))}${metric('ارزش بازار',money(p.market_cap,true))}${metric('ارزش کاملاً رقیق‌شده (FDV)',money(p.fdv,true))}${metric('قیمت در ارز مقابل',p.price_native===null||p.price_native===undefined?'—':`<bdi>${num(p.price_native,{maximumFractionDigits:12,notation:p.price_native!==0&&Math.abs(p.price_native)<1e-10?'scientific':'standard'})} ${e(p.quote)}</bdi>`)}</div><p class="hint">تعداد خرید و فروش، تعداد تراکنش‌هاست؛ تعداد معامله‌گران یکتا نیست.</p>${p.created_at?`<p class="muted">ایجاد جفت: ${e(date(new Date(p.created_at).toISOString()))}</p>`:''}<p class="muted">آدرس قرارداد توکن پایه · هویت توکن تأیید نشده</p><p class="contract" dir="ltr">${e(p.token_address)}</p>${link(p.url,'نمودار شمعی و ریز معاملات در DEX Screener')}<p class="hint">نمودار شمعی و ریز معاملات از ویجت رسمی منبع نمایش داده می‌شوند؛ آمار فارسی بالا از کش سایت است و ممکن است زمان آن متفاوت باشد.</p>`;
}
