export const DEMO_TIME='2026-10-05T08:00:00Z';
export const coinNames={1:'بیت‌کوین',1027:'اتریوم',825:'تتر',1839:'بی‌ان‌بی',5426:'سولانا'};
export function demoMarket(){const ids=[1,1027,825,1839,5426],symbols=['BTC','ETH','USDT','BNB','SOL'],prices=[62450.25,2480.6,1,580.4,145.12];return {mode:'demo',fetched_at:DEMO_TIME,freshness:'demo',items:Array.from({length:100},(_,i)=>({id:ids[i]??900000+i,rank:i+1,name:coinNames[ids[i]]??`کوین نمونه ${i+1}`,symbol:symbols[i]??`DEMO${i+1}`,price:prices[i]??(i===99?1.23e-11:1000/(i+1)),change_24h:i%2?-1.7-i/80:2.4+i/50,volume_24h:250000000/(i+1),market_cap:1200000000/(i+1)}))};}
export const demoNews=[{id:'demo-1',title_fa:'بیت‌کوین چیست و شبکه آن چگونه کار می‌کند؟',summary_fa:'این خبر نمونه برای بررسی تجربه خواندن فارسی ساخته شده است. بیت‌کوین یک شبکه پرداخت همتابه‌همتاست؛ برای مطالعه بیشتر به منبع مراجعه کنید.',publisher:'نمونه آموزشی نبض کوین',url:'https://bitcoin.org/fa/',published_at:'2026-10-05T07:00:00Z',coin_ids:[1],demo:true,translation_status:'fixture'},{id:'demo-2',title_fa:'آشنایی با ارزش بازار و حجم معاملات',summary_fa:'در این محتوای نمونه، ارزش بازار از حاصل‌ضرب قیمت در عرضه در گردش محاسبه می‌شود. حجم معاملات و ارزش بازار دو معیار متفاوت‌اند. این متن خبر واقعی نیست.',publisher:'نمونه آموزشی نبض کوین',url:'https://coinmarketcap.com/academy',published_at:'2026-10-05T06:00:00Z',coin_ids:[1027],demo:true,translation_status:'fixture'}];
export function demoChart(coin,range){const days={'1d':1,'7d':7,'30d':30}[range];if(!days)throw Error('Invalid range');return {mode:'demo',fetched_at:DEMO_TIME,freshness:'demo',source:'demo',points:Array.from({length:48},(_,i)=>({time:new Date(Date.parse(DEMO_TIME)-(47-i)*days*86400000/47).toISOString(),price:coin.price*(.97+i/1600+Math.sin(i*.5)*.008)}))};}
export function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function usd(value,persian=true,compact=false){if(value==null||!Number.isFinite(Number(value)))return '—';return new Intl.NumberFormat(persian?'fa-IR':'en-US',{style:'currency',currency:'USD',notation:compact?'compact':value!==0&&Math.abs(value)<.000001?'scientific':'standard',maximumFractionDigits:compact?2:Math.abs(value)<1?8:2}).format(value);}
export function date(value){if(!value||Number.isNaN(Date.parse(value)))return 'زمان نامشخص';return new Intl.DateTimeFormat('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
export function relative(value,now=Date.now()){const elapsed=(Date.parse(value)-now)/1000;if(!Number.isFinite(elapsed))return 'زمان نامشخص';const [unit,size]=Math.abs(elapsed)<60?['second',1]:Math.abs(elapsed)<3600?['minute',60]:Math.abs(elapsed)<86400?['hour',3600]:['day',86400];return new Intl.RelativeTimeFormat('fa-IR',{numeric:'auto'}).format(Math.round(elapsed/size),unit);}
export function selectCoins(items,{query='',sort='rank',watch=null}={}){const q=query.trim().toLocaleLowerCase();return items.filter(c=>(!watch||watch.includes(c.id))&&`${coinNames[c.id]??c.name} ${c.name} ${c.symbol}`.toLocaleLowerCase().includes(q)).sort((a,b)=>sort==='gainers'?b.change_24h-a.change_24h:sort==='losers'?a.change_24h-b.change_24h:a.rank-b.rank);}
export function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export function chartPath(points,width=900,height=250){const sorted=points.filter(p=>Number.isFinite(p.price)&&Number.isFinite(Date.parse(p.time))).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));if(!sorted.length)return '';const min=Math.min(...sorted.map(p=>p.price)),max=Math.max(...sorted.map(p=>p.price)),first=Date.parse(sorted[0].time),span=Date.parse(sorted.at(-1).time)-first;return sorted.map((p,i)=>`${i?'L':'M'}${(span?(Date.parse(p.time)-first)/span*(width-24)+12:width/2).toFixed(2)},${(max===min?height/2:height-12-(p.price-min)/(max-min)*(height-24)).toFixed(2)}`).join(' ');}
export class APIError extends Error{constructor(status){super(`API ${status}`);this.status=status;}}
export class DataClient{
 constructor({mode='demo',storage=globalThis.localStorage,fetcher=globalThis.fetch,namespace=globalThis.location?.origin??'test'}={}){this.mode=mode;this.storage=storage;this.fetcher=fetcher.bind(globalThis);this.namespace=namespace;}
 async get(path,{signal}={}){if(this.mode!=='live')throw Error('Demo uses fixtures explicitly');const key=`nabz:live:${this.namespace}:${path}`;try{const response=await this.fetcher(path,{signal:signal??AbortSignal.timeout(12000),headers:{Accept:'application/json'}});if(!response.ok)throw new APIError(response.status);const body=await response.json();if(('mode'in body&&body.mode!=='live')||body.demo===true)throw new APIError(409);if(!('mode'in body)&&!('demo'in body))throw new APIError(502);const stamped={...body,_received_at:new Date().toISOString()};try{this.storage?.setItem(key,JSON.stringify(stamped));}catch{}return stamped;}catch(error){if(error.name==='AbortError'||error instanceof APIError&&error.status<500)throw error;let cached;try{cached=JSON.parse(this.storage?.getItem(key)??'null');}catch{}if(!cached)throw error;return {...cached,_offline:true};}}
}
