import {dexDetails,dexEmbedURL} from './analytics.js?v=27';
import {selectPairs} from './discovery-ui.js?v=27';
export function renderDex(host,data,ctx){
 const {e,num,money,date,link}=ctx;
 const names={pairs:'جفت‌ها',profiles:'پروفایل‌های جدید',updates:'پروفایل‌های به‌روز',community:'واگذاری به جامعه',metas:'دسته‌های ترند',boosts:'Boost جدید',top_boosts:'بیشترین Boost',ads:'تبلیغات',orders:'سفارش‌های تبلیغاتی',api:'داده و API'};
 let selected='pairs',query='',chain='',sort='volume_24h',origin='',limit=30;
 host.innerHTML=`<p class="hint">بازارهای جست‌وجوی BTC/ETH/SOL، توکن‌های فید عمومی و دسته‌های ترند. این مجموعه کل بازار DEX نیست؛ هویت هر توکن با شبکه و آدرس قرارداد مشخص می‌شود. Boost و تبلیغ، پرداخت برای دیده‌شدن هستند.</p><nav class="dex-feed-tabs" aria-label="داده‌های DEX">${Object.entries(names).map(([key,label])=>`<button data-feed="${key}" aria-pressed="${key==='pairs'}">${label}</button>`).join('')}</nav><div id="dex-feed-content"></div>`;
 const output=host.querySelector('#dex-feed-content');
 const metric=(label,value)=>`<div class="dex-metric"><span>${label}</span><strong>${value}</strong></div>`;
 const tokenName=p=>{const match=data.items.find(x=>x.chain===(p.chainId||p.chain)&&x.token_address===(p.tokenAddress||p.address));return match?.name?e(match.name)+' <bdi>'+e(match.base)+'</bdi>':e(p.chainId||p.chain);};
 const metaChanges=p=>`<details><summary>تغییر ارزش بازار در چهار بازه</summary><div class=explore-table><table><thead><tr><th>بازه</th><th>درصد</th><th>تغییر دلاری</th></tr></thead><tbody>${Object.entries({m5:'۵ دقیقه',h1:'۱ ساعت',h6:'۶ ساعت',h24:'۲۴ ساعت'}).map(([k,label])=>`<tr><td>${label}</td><td>${p.marketCapChange?.[k]==null?'—':num(p.marketCapChange[k],{maximumFractionDigits:2})+'%'}</td><td>${money(p.marketCapDelta?.[k],true)}</td></tr>`).join('')}</tbody></table></div></details>`;
 const contract=a=>`<p class="contract" dir="ltr">${e(a||'—')}</p>`;
 function render(){
  if(selected==='pairs'){
   output.innerHTML=`<section class="panel dex-panel"><div class="dex-toolbar"><div><h2>جفت‌های معاملاتی</h2><p id="dex-count" role="status"></p></div><div><label for="dex-query">جست‌وجوی نماد یا قرارداد</label><input id="dex-query" type="search" placeholder="نام، نماد یا آدرس دقیق قرارداد" value="${e(query)}"></div><div><label for="dex-chain">شبکه</label><select id="dex-chain"><option value="">همه شبکه‌ها</option>${[...new Set(data.items.map(p=>p.chain))].sort().map(c=>`<option value="${e(c)}">${e(c)}</option>`).join('')}</select></div><div><label for="dex-sort">مرتب‌سازی</label><select id="dex-sort"><option value="volume_24h">حجم ۲۴ ساعت</option><option value="liquidity">نقدینگی</option><option value="change">رشد ۲۴ ساعت</option><option value="transactions">تعداد تراکنش</option><option value="created_at">جدیدترین جفت</option></select></div></div><div class="dex-list"></div><div class="table-bottom"><button id="dex-more">نمایش ۳۰ جفت دیگر</button></div></section>`;
   output.querySelector('#dex-chain').value=chain;output.querySelector('#dex-sort').value=sort;
   const refresh=()=>{
    const items=selectPairs(data.items,{query,chain,sort,origin});
    output.querySelector('#dex-count').textContent=`${num(Math.min(limit,items.length))} از ${num(items.length)} جفت؛ کل مجموعه ${num(data.items.length)}`;
    output.querySelector('.dex-list').innerHTML=items.slice(0,limit).map(p=>`<article class="dex-row"><div class="dex-identity"><h3><bdi>${e(p.base)} / ${e(p.quote)}</bdi></h3><p><span class="badge">${e(p.chain)}</span> <bdi>${e(p.dex)}</bdi></p>${p.boosts?.active?'<span class="badge">Boost پولی</span>':''}</div>${metric('قیمت USD',money(p.price))}${metric('حجم ۲۴ ساعت',money(p.volume_24h,true))}${metric('نقدینگی',money(p.liquidity,true))}<details class="dex-details" data-pair="${e(p.chain+'|'+p.address)}"><summary>آمار کامل، قرارداد و نمودار</summary><div class="dex-analysis-body"></div><button data-dex-chart aria-expanded="false">نمایش نمودار شمعی و معاملات</button><div class="dex-chart-host"></div></details></article>`).join('')||'<p class="empty">جفتی پیدا نشد.</p>';
    output.querySelector('#dex-more').hidden=items.length<=limit;
   };
   output.querySelector('#dex-query').addEventListener('input',ev=>{query=ev.target.value;limit=30;refresh();});
   output.querySelector('#dex-chain').addEventListener('change',ev=>{chain=ev.target.value;limit=30;refresh();});
   output.querySelector('#dex-sort').addEventListener('change',ev=>{sort=ev.target.value;limit=30;refresh();});
   output.querySelector('#dex-more').onclick=()=>{limit+=30;refresh();};refresh();return;
  }
  if(selected==='api'){
   output.innerHTML=`<section class="panel"><h2>پوشش API و خروجی داده</h2><p>${num(data.endpoint_catalog?.length||0)} مسیر مستند API؛ فقط پاسخ‌های دریافت‌شده در این اسنپ‌شات قابل دانلود هستند. سقف توکن ${num(data.scope?.token_limit||0)}، دسته ${num(data.scope?.meta_limit||0)} و سفارش تبلیغاتی ${num(data.scope?.order_limit||0)}.</p><button data-download class="primary">دانلود تمام پاسخ‌های دریافت‌شده (JSON)</button><div class="explore-table"><table><thead><tr><th>مسیر API</th></tr></thead><tbody>${(data.endpoint_catalog||[]).map(path=>`<tr><td class="contract" dir="ltr">${e(path)}</td></tr>`).join('')}</tbody></table></div><h3>وضعیت منابع</h3>${Object.entries(data.statuses||{}).map(([k,v])=>`<p><bdi>${e(names[k]||k)}</bdi>: ${v==='ready'?'دریافت شد':v==='partial'?'دریافت ناقص':'در دسترس نبود'}</p>`).join('')}<p class="hint">این API عمومی داده تاریخی OHLC و فهرست همه معاملات یا دارندگان را ارائه نمی‌کند؛ نمودار و معاملات با ویجت منبع نمایش داده می‌شوند.</p></section>`;return;
  }
  const rows=selected==='orders'?data.orders||[]:data.feeds?.[selected]||[];
  const paid=['boosts','top_boosts','ads','orders'].includes(selected);
  output.innerHTML=`<section><h2>${e(names[selected])} · ${num(rows.length)}</h2><p class="hint">${paid?'داده تبلیغاتی و پولی؛ رتبه Boost معیار بازده، امنیت یا محبوبیت طبیعی نیست.':selected==='community'?'ادعای واگذاری به جامعه در منبع؛ تأیید سازنده یا مالکیت پروژه نیست.':'اطلاعات منتشرشده در منبع؛ هویت و ادعاهای پروژه مستقل تأیید نشده‌اند.'}</p><div class="data-card-grid">${rows.map(p=>selected==='metas'?`<article class="panel dex-feed-card"><h3 dir="auto">${e(p.name)}</h3><p dir="auto">${e(p.description)}</p>${metric('تعداد توکن',num(p.tokenCount))}${metric('حجم',money(p.volume,true))}${metric('نقدینگی',money(p.liquidity,true))}${metric('ارزش بازار',money(p.marketCap,true))}${metaChanges(p)}<button data-meta="${e(p.slug)}">جفت‌های این دسته</button>${link('https://dexscreener.com/metas/'+encodeURIComponent(p.slug),'صفحه دسته در منبع')}</article>`:`<article class="panel dex-feed-card"><h3>${tokenName(p)} ${paid?'<span class="badge">تبلیغاتی</span>':''}</h3>${contract(p.tokenAddress||p.address)}${p.description?`<p dir="auto">${e(p.description)}</p>`:''}${p.totalAmount!==undefined?metric('مجموع Boost',num(p.totalAmount)):''}${p.amount!==undefined?metric('Boost این نوبت',num(p.amount)):''}${p.impressions!==undefined?metric('نمایش تبلیغ',num(p.impressions)):''}${p.durationHours!==undefined?metric('مدت تبلیغ (ساعت)',num(p.durationHours)):''}${p.type?`<p dir="auto">${e(p.type)}</p>`:''}${p.updatedAt||p.claimDate||p.date?`<p>${e(date(p.updatedAt||p.claimDate||p.date))}</p>`:''}${selected==='orders'?`<p>سفارش ثبت‌شده: ${num(Array.isArray(p.data)?p.data.length:p.data?.orders?.length||0)} · Boost: ${num(p.data?.boosts?.length||0)}</p><details><summary>جزئیات سفارش منبع</summary><pre class="raw-json" dir="ltr">${e(JSON.stringify(p.data,null,2))}</pre></details>`:''}${link(p.url,'صفحه منبع')}${(p.links||[]).map(x=>link(x.url,x.label||x.type||'لینک پروژه')).join(' ')}<button data-token="${e(p.tokenAddress||p.address)}" data-chain="${e(p.chainId||p.chain)}">جفت‌های این قرارداد</button></article>`).join('')||'<p class="empty">منبع در این نوبت داده‌ای ارائه نکرده است.</p>'}</div></section>`;
 }
 const pairFor=details=>data.items.find(p=>p.chain+'|'+p.address===details.dataset.pair);
 output.addEventListener('toggle',event=>{const details=event.target.closest('[data-pair]');if(details?.open){const body=details.querySelector('.dex-analysis-body');if(!body.innerHTML)body.innerHTML=dexDetails(pairFor(details),ctx);}},true);
 host.addEventListener('click',async event=>{
  const b=event.target.closest('button');if(!b)return;
  if(b.dataset.feed){selected=b.dataset.feed;origin='';host.querySelectorAll('[data-feed]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();return;}
  if(b.hasAttribute('data-download')){b.disabled=true;const label=b.textContent;b.textContent='آماده‌سازی فایل…';try{const snapshot=await ctx.client.get('/api/v1/discovery/dex?include_raw=true');if(!snapshot.raw)throw Error('Missing raw response');const url=URL.createObjectURL(new Blob([JSON.stringify({fetched_at:snapshot.fetched_at,scope:snapshot.scope,responses:snapshot.raw},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='nabz-dex-snapshot.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);b.textContent=label;}catch{b.textContent='دانلود ناموفق؛ دوباره تلاش کنید';}finally{b.disabled=false;}return;}
  if(b.hasAttribute('data-token')||b.hasAttribute('data-meta')){query=b.dataset.token||'';chain=b.dataset.chain||'';origin=b.dataset.meta?'meta:'+b.dataset.meta:'';selected='pairs';limit=30;host.querySelectorAll('[data-feed]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.feed==='pairs'));render();output.querySelector('#dex-query').focus();return;}
  const details=b.closest('[data-pair]');if(!details)return;const p=pairFor(details);
  if(b.dataset.dexPeriod){const body=details.querySelector('.dex-analysis-body');body.innerHTML=dexDetails(p,ctx,b.dataset.dexPeriod);body.querySelector(`[data-dex-period="${b.dataset.dexPeriod}"]`)?.focus();}
  if(b.hasAttribute('data-dex-chart')){const target=details.querySelector('.dex-chart-host');if(target.innerHTML){target.innerHTML='';b.textContent='نمایش نمودار شمعی و معاملات';b.setAttribute('aria-expanded','false');return;}const url=dexEmbedURL(p,document.documentElement.dataset.theme);if(!url)return;target.innerHTML=`<iframe class="dex-embed" title="${e(p.base)} / ${e(p.quote)} — DEX Screener" src="${e(url)}" loading="lazy" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-popups"></iframe>`;b.textContent='بستن نمودار';b.setAttribute('aria-expanded','true');}
 });
 render();
}
