export async function renderExplore({main,client,e,num,money,date,safeURL,current}){
 const tabs={sentiment:'ترس و طمع',defi:'دیفای',dex:'بازار DEX',projects:'اطلاعات پروژه‌ها'};
 const key=new URLSearchParams(location.hash.split('?')[1]).get('tab')||'sentiment';
 const selected=key in tabs?key:'sentiment';
 const data=client.mode==='demo'?{items:[],freshness:'unavailable'}:await client.get(`/api/v1/discovery/${selected}`);if(!current())return;
 const link=(url,label)=>safeURL(url)?`<a class="text-link" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`:'';
 let content='';
 if(!data.items.length)content='<div class="empty panel"><h2>داده این بخش هنوز آماده نیست</h2><p>دریافت دوره‌ای یا تنظیمات منبع را بررسی کنید.</p></div>';
 else if(selected==='sentiment'){
 const labels={'Extreme Fear':'ترس شدید',Fear:'ترس',Neutral:'خنثی',Greed:'طمع','Extreme Greed':'طمع شدید'};
 const first=data.items[0];content=`<section class="panel"><h2>احساسات بازار بیت‌کوین</h2><p class="sentiment-number">${num(first.value)} <small>از ${num(100)}</small></p><meter min="0" max="100" value="${first.value}" aria-label="شاخص ترس و طمع">${first.value}</meter><p>${e(labels[first.classification]||first.classification)}</p><p>زمان شاخص: ${e(date(first.time))}</p>${link(data.source_url,'منبع: Alternative.me')}<p class="muted">این شاخص عمدتاً مربوط به بیت‌کوین است و سیگنال خرید یا فروش نیست.</p></section><section class="panel"><h2>تاریخچه روزانه</h2><div class="explore-table"><table><thead><tr><th>تاریخ</th><th>شاخص</th><th>وضعیت</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${e(date(x.time))}</td><td>${num(x.value)}</td><td>${e(labels[x.classification]||x.classification)}</td></tr>`).join('')}</tbody></table></div></section>`;
 }else if(selected==='defi'){
 content=`<p class="hint">TVL ارزش دارایی قفل‌شده در پروتکل است؛ با ارزش بازار توکن تفاوت دارد. ارقام پروتکل‌ها را نباید بدون بررسی دوباره‌شماری جمع زد.</p><section class="panel"><h2>پروتکل‌ها بر اساس TVL</h2><label for="explore-search">جست‌وجوی نام یا دسته‌بندی</label><input id="explore-search" type="search" placeholder="مثلاً Aave"><div class="explore-table"><table><thead><tr><th>پروتکل</th><th>دسته</th><th>شبکه‌ها</th><th>TVL</th></tr></thead><tbody>${data.items.map(p=>`<tr data-filter="${e((p.name+' '+p.category).toLowerCase())}"><td>${link('https://defillama.com/protocol/'+encodeURIComponent(p.slug),p.name)}</td><td>${e(p.category)}</td><td><details><summary>${num(p.chains.length)} شبکه</summary>${e(p.chains.join('، '))}</details></td><td>${money(p.tvl,true)}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>TVL زنجیره‌ها</h2><div class="data-card-grid">${(data.chains||[]).map(p=>`<div class="data-card"><h3>${e(p.name)}</h3>${money(p.tvl,true)}</div>`).join('')}</div></section>`;
 }else if(selected==='dex'){
 content=`<p class="hint">نتایج جست‌وجوی نماد BTC، ETH و SOL در DEX Screener، بر اساس حجم ۲۴ ساعت؛ نام نماد، هویت یا اصالت توکن را تضمین نمی‌کند. شبکه و آدرس قرارداد را بررسی کنید.</p><label for="explore-search">جست‌وجوی نماد یا شبکه</label><input id="explore-search" type="search"><div class="data-card-grid">${data.items.map(p=>`<article class="panel" data-filter="${e((p.base+' '+p.quote+' '+p.chain).toLowerCase())}"><h2><bdi>${e(p.base)} / ${e(p.quote)}</bdi></h2><p>${e(p.chain)} · ${e(p.dex)}</p><p class="hint">نتیجه جست‌وجو؛ هویت توکن تأیید نشده</p><dl><dt>قیمت دلاری این جفت</dt><dd>${money(p.price)}</dd><dt>نقدینگی</dt><dd>${money(p.liquidity,true)}</dd><dt>حجم ۲۴ ساعت</dt><dd>${money(p.volume_24h,true)}</dd></dl><details><summary>آدرس قرارداد توکن</summary><p class="contract" dir="ltr">${e(p.token_address)}</p></details>${link(p.url,'مشاهده جفت در منبع')}</article>`).join('')}</div>`;
 }else{
 content=`<p class="hint">داده تکمیلی انگلیسی از CoinPaprika؛ اعضای تیم ممکن است توسعه‌دهنده یا مشارکت‌کننده باشند و الزاماً بنیان‌گذار نیستند.</p><div class="data-card-grid">${data.items.map(p=>`<article class="panel"><h2>${e(p.name)} <bdi>${e(p.symbol)}</bdi></h2><details><summary>شرح پروژه به زبان منبع</summary><p dir="auto">${e(p.description||'توضیح موجود نیست')}</p></details><h3>تیم ثبت‌شده در منبع</h3><ul>${p.team.map(t=>`<li dir="auto">${e(t.name)} — ${e(t.position)}</li>`).join('')||'<li>اطلاعات موجود نیست</li>'}</ul>${link(p.source_url,'صفحه پروژه و منابع')}</article>`).join('')}</div>`;
 }
 main.innerHTML=`<div class="heading"><div><h1>کاوش داده‌های کریپتو</h1><p class="subtitle">احساسات بازار، دیفای، معاملات آن‌چین و اطلاعات پروژه‌ها</p></div></div><nav class="explore-tabs" aria-label="داده‌های کاوش">${Object.entries(tabs).map(([k,label])=>`<a class="action-link ${selected===k?'primary':''}" href="#explore?tab=${k}" ${selected===k?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${data.fetched_at?`<p class="muted">دریافت: ${e(date(data.fetched_at))}${data.freshness==='stale'?' · داده قدیمی':data._offline?' · نسخه آفلاین':''}</p>`:''}${data.source_url?`<p>${link(data.source_url,selected==='projects'?'Powered by CoinPaprika':'منبع: '+data.source)}</p>`:''}<div class="explore-content">${content}</div>`;
 const input=main.querySelector('#explore-search');if(input)input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();main.querySelectorAll('[data-filter]').forEach(row=>row.hidden=!row.dataset.filter.includes(q));});
}
