import {renderDex} from './dex-browser.js?v=27';
import {sortProtocols} from './discovery-ui.js?v=27';
import {sentimentOverview,renderProtocolBrowser} from './analytics.js?v=27';
export async function renderExplore({main,client,e,num,money,date,safeURL,current}){
 const tabs={sentiment:'ترس و طمع',defi:'دیفای',dex:'بازار DEX',projects:'اطلاعات پروژه‌ها'};
 const key=new URLSearchParams(location.hash.split('?')[1]).get('tab')||'sentiment';
 const selected=key in tabs?key:'sentiment';
 const data=client.mode==='demo'?{items:[],freshness:'unavailable'}:await client.get(`/api/v1/discovery/${selected}`);if(!current())return;
 const link=(url,label)=>safeURL(url)?`<a class="text-link" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`:'';
 let content='';
 if(!data.items.length&&!(selected==='dex'&&Object.values(data.feeds||{}).some(rows=>rows.length)))content='<div class="empty panel"><h2>داده این بخش هنوز آماده نیست</h2><p>دریافت دوره‌ای یا تنظیمات منبع را بررسی کنید.</p></div>';
 else if(selected==='sentiment'){
 const labels={'Extreme Fear':'ترس شدید',Fear:'ترس',Neutral:'خنثی',Greed:'طمع','Extreme Greed':'طمع شدید'};
 const history=[...data.items].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));const start=Date.parse(history[0].time),span=Date.parse(history.at(-1).time)-start;const trend=history.map((p,i)=>`${i?'L':'M'}${span?12+(Date.parse(p.time)-start)/span*876:450},${238-p.value/100*226}`).join(' ');const first=data.items[0];content=`${sentimentOverview(data,{e,num,date,link})}<section class="panel"><h2>روند احساسات در ۳۱ روز گذشته</h2><div class="price-plot"><div class="price-axis" aria-hidden="true">${[100,75,50,25,0].map(v=>`<span>${num(v)}</span>`).join('')}</div><svg class="chart" preserveAspectRatio="none" viewBox="0 0 900 250" role="img" aria-label="روند شاخص ترس و طمع از صفر تا صد؛ جزئیات در جدول زیر">${[12,68.5,125,181.5,238].map(y=>`<line x1="12" x2="888" y1="${y}" y2="${y}" stroke="var(--border)" stroke-dasharray="4 6"/>`).join('')}<path d="${trend}" fill="none" stroke="var(--accent)" stroke-width="3" vector-effect="non-scaling-stroke"/></svg></div><div class="chart-times" dir="ltr"><span>${e(date(history[0].time))}</span><span>${e(date(history.at(-1).time))}</span></div><details><summary>جدول مقادیر روزانه</summary><div class="explore-table"><table><thead><tr><th>تاریخ</th><th>شاخص</th><th>وضعیت</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${e(date(x.time))}</td><td>${num(x.value)}</td><td>${e(labels[x.classification]||x.classification)}</td></tr>`).join('')}</tbody></table></div></details></section>`;
 }else if(selected==='defi'){
 content=`<section class="panel"><h2>بیشترین رشد TVL در ۳۰ روز گذشته</h2><details class="methodology"><summary>روش محاسبه و دامنه پوشش (۱۰۰ پروتکل)</summary><p class="hint">TVL ارزش دارایی قفل‌شده در پروتکل است، نه ارزش بازار توکن. مقایسه میان ۱۰۰ پروتکل بزرگ بر اساس TVL فعلی؛ درصد رشد نسبت به نزدیک‌ترین روز ثبت‌شده در ۳۰ روز قبل محاسبه شده است. سابقه ناکافی با «—» مشخص می‌شود و انتهای فهرست قرار می‌گیرد. رشد دلاری TVL می‌تواند از تغییر قیمت دارایی‌ها هم ناشی شود.</p></details>${data.growth_calculated_at?`<p class="muted">محاسبه رشد: ${e(date(data.growth_calculated_at))}${Date.now()-Date.parse(data.growth_fetched_at)>43200000?' · داده رشد قدیمی':''}</p>`:'<p class="muted">تاریخچه ماهانه هنوز دریافت نشده است.</p>'}<div class="defi-toolbar"><div><label for="explore-search">جست‌وجوی نام یا دسته‌بندی</label><input id="explore-search" type="search" placeholder="مثلاً Aave"></div><div><label for="defi-sort">مرتب‌سازی پروتکل‌ها</label><select id="defi-sort"><option value="change_30d">بیشترین رشد TVL در ۳۰ روز</option><option value="delta_30d">بیشترین افزایش دلاری TVL</option><option value="tvl">بیشترین TVL فعلی</option></select></div></div><div class="explore-table"><table><thead><tr><th>پروتکل</th><th>دسته / شبکه</th><th>TVL فعلی</th><th>رشد ۳۰ روز</th><th>افزایش دلاری ۳۰ روز</th></tr></thead><tbody id="defi-rows"></tbody></table></div></section><section class="panel" id="protocol-analytics"></section><section class="panel"><h2>TVL زنجیره‌ها</h2><div class="data-card-grid">${(data.chains||[]).map(p=>`<div class="data-card"><h3>${e(p.name)}</h3>${money(p.tvl,true)}</div>`).join('')}</div></section>`;
 }else if(selected==='dex'){
 content='<section id="dex-browser"></section>';
 }else{
 content=`<p class="hint">داده تکمیلی انگلیسی از CoinPaprika؛ اعضای تیم ممکن است توسعه‌دهنده یا مشارکت‌کننده باشند و الزاماً بنیان‌گذار نیستند.</p><div class="data-card-grid">${data.items.map(p=>`<article class="panel"><h2>${e(p.name)} <bdi>${e(p.symbol)}</bdi></h2><details><summary>شرح پروژه به زبان منبع</summary><p dir="auto">${e(p.description||'توضیح موجود نیست')}</p></details><h3>تیم ثبت‌شده در منبع</h3><ul>${p.team.map(t=>`<li dir="auto">${e(t.name)} — ${e(t.position)}</li>`).join('')||'<li>اطلاعات موجود نیست</li>'}</ul>${link(p.source_url,'صفحه پروژه و منابع')}</article>`).join('')}</div>`;
 }
 main.innerHTML=`<div class="heading"><div><h1>کاوش داده‌های کریپتو</h1><p class="subtitle">احساسات بازار، دیفای، معاملات آن‌چین و اطلاعات پروژه‌ها</p></div></div><nav class="explore-tabs" aria-label="داده‌های کاوش">${Object.entries(tabs).map(([k,label])=>`<a class="action-link ${selected===k?'primary':''}" href="#explore?tab=${k}" ${selected===k?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${data.fetched_at?`<p class="muted">دریافت: ${e(date(data.fetched_at))}${data.freshness==='stale'?' · داده قدیمی':data._offline?' · نسخه آفلاین':''}</p>`:''}${data.source_url?`<p>${link(data.source_url,selected==='projects'?'Powered by CoinPaprika':'منبع: '+data.source)}</p>`:''}<div class="explore-content">${content}</div>`;
 const ctx={client,current,e,num,money,date,link};if(selected==='dex'){const host=main.querySelector('#dex-browser');if(host)renderDex(host,data,ctx);return;}if(selected==='defi'&&data.items.length){const rows=main.querySelector('#defi-rows');const draw=()=>{rows.innerHTML=sortProtocols(data.items,main.querySelector('#defi-sort').value).map(p=>`<tr data-filter="${e((p.name+' '+p.category).toLowerCase())}"><td>${link('https://defillama.com/protocol/'+encodeURIComponent(p.slug),p.name)}</td><td>${e(p.category)}<details><summary>${num(p.chains.length)} شبکه</summary>${e(p.chains.join('، '))}</details></td><td>${money(p.tvl,true)}</td><td title="${p.baseline_at?e('تاریخ مبنا: '+date(p.baseline_at)):''}">${typeof p.change_30d==='number'?`<bdi class="${p.change_30d>=0?'positive':'negative'}">${p.change_30d>0?'+':''}${num(p.change_30d,{maximumFractionDigits:2})}%</bdi>`:'—'}</td><td>${money(p.delta_30d,true)}</td></tr>`).join('');const q=main.querySelector('#explore-search').value.trim().toLowerCase();rows.querySelectorAll('[data-filter]').forEach(row=>row.hidden=!row.dataset.filter.includes(q));};draw();main.querySelector('#defi-sort').addEventListener('change',draw);}const protocol=main.querySelector('#protocol-analytics');if(protocol&&client.mode!=='demo')await renderProtocolBrowser(protocol,ctx);if(!current())return;
 const input=main.querySelector('#explore-search');const filter=()=>{const q=input?.value.trim().toLowerCase()||'';let count=0;main.querySelectorAll('[data-filter]').forEach(row=>{row.hidden=!row.dataset.filter.includes(q);if(!row.hidden)count++;});const output=main.querySelector('#dex-count');if(output)output.textContent=`${num(count)} جفت قابل نمایش`;const empty=main.querySelector('#dex-empty');if(empty)empty.hidden=count>0;};if(input){input.addEventListener('input',filter);filter();}
}

