import {sentimentOverview,renderProtocolBrowser,dexDetails,dexEmbedURL} from './analytics.js?v=22';
export async function renderExplore({main,client,e,num,money,date,safeURL,current}){
 const tabs={sentiment:'ترس و طمع',defi:'دیفای',dex:'بازار DEX',projects:'اطلاعات پروژه‌ها'};
 const key=new URLSearchParams(location.hash.split('?')[1]).get('tab')||'sentiment';
 const selected=key in tabs?key:'sentiment';
 const data=client.mode==='demo'?{items:[],freshness:'unavailable'}:await client.get(`/api/v1/discovery/${selected}`);if(!current())return;
 const link=(url,label)=>safeURL(url)?`<a class="text-link" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`:'';
 let content='';
 if(!data.items.length)content='<div class="empty panel"><h2>داده این بخش هنوز آماده نیست</h2><p>دریافت دوره‌ای یا تنظیمات منبع را بررسی کنید.</p></div>';
 else if(selected==='sentiment'){
 const labels={'Extreme Fear':'ترس شدید',Fear:'ترس',Neutral:'خنثی',Greed:'طمع','Extreme Greed':'طمع شدید'};
 const history=[...data.items].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));const start=Date.parse(history[0].time),span=Date.parse(history.at(-1).time)-start;const trend=history.map((p,i)=>`${i?'L':'M'}${span?12+(Date.parse(p.time)-start)/span*876:450},${238-p.value/100*226}`).join(' ');const first=data.items[0];content=`${sentimentOverview(data,{e,num,date,link})}<section class="panel"><h2>روند احساسات در ۳۱ روز گذشته</h2><div class="price-plot"><div class="price-axis" aria-hidden="true">${[100,75,50,25,0].map(v=>`<span>${num(v)}</span>`).join('')}</div><svg class="chart" preserveAspectRatio="none" viewBox="0 0 900 250" role="img" aria-label="روند شاخص ترس و طمع از صفر تا صد؛ جزئیات در جدول زیر">${[12,68.5,125,181.5,238].map(y=>`<line x1="12" x2="888" y1="${y}" y2="${y}" stroke="var(--border)" stroke-dasharray="4 6"/>`).join('')}<path d="${trend}" fill="none" stroke="var(--accent)" stroke-width="3" vector-effect="non-scaling-stroke"/></svg></div><div class="chart-times" dir="ltr"><span>${e(date(history[0].time))}</span><span>${e(date(history.at(-1).time))}</span></div><details><summary>جدول مقادیر روزانه</summary><div class="explore-table"><table><thead><tr><th>تاریخ</th><th>شاخص</th><th>وضعیت</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${e(date(x.time))}</td><td>${num(x.value)}</td><td>${e(labels[x.classification]||x.classification)}</td></tr>`).join('')}</tbody></table></div></details></section>`;
 }else if(selected==='defi'){
 content=`<section class="panel" id="protocol-analytics"></section><p class="hint">TVL ارزش دارایی قفل‌شده در پروتکل است؛ با ارزش بازار توکن تفاوت دارد. ارقام پروتکل‌ها را نباید بدون بررسی دوباره‌شماری جمع زد.</p><section class="panel"><h2>پروتکل‌ها بر اساس TVL</h2><label for="explore-search">جست‌وجوی نام یا دسته‌بندی</label><input id="explore-search" type="search" placeholder="مثلاً Aave"><div class="explore-table"><table><thead><tr><th>پروتکل</th><th>دسته</th><th>شبکه‌ها</th><th>TVL</th></tr></thead><tbody>${data.items.map(p=>`<tr data-filter="${e((p.name+' '+p.category).toLowerCase())}"><td>${link('https://defillama.com/protocol/'+encodeURIComponent(p.slug),p.name)}</td><td>${e(p.category)}</td><td><details><summary>${num(p.chains.length)} شبکه</summary>${e(p.chains.join('، '))}</details></td><td>${money(p.tvl,true)}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>TVL زنجیره‌ها</h2><div class="data-card-grid">${(data.chains||[]).map(p=>`<div class="data-card"><h3>${e(p.name)}</h3>${money(p.tvl,true)}</div>`).join('')}</div></section>`;
 }else if(selected==='dex'){
 content=`<p class="hint">جفت‌های BTC، ETH و SOL بر اساس حجم معاملات ۲۴ ساعت. هر جفت متعلق به شبکه و قرارداد مشخصی است؛ نماد به‌تنهایی هویت توکن را تأیید نمی‌کند.</p><section class="panel dex-panel"><div class="dex-toolbar"><div><h2>جفت‌های معاملاتی</h2><p class="muted" id="dex-count" role="status"></p></div><div><label for="explore-search">جست‌وجوی نماد، شبکه یا صرافی</label><input id="explore-search" type="search" placeholder="مثلاً SOL یا uniswap"></div><div><label for="dex-sort">مرتب‌سازی</label><select id="dex-sort"><option value="volume_24h">بیشترین حجم ۲۴ ساعت</option><option value="liquidity">بیشترین نقدینگی</option></select></div></div><div class="dex-list">${data.items.map((p,index)=>`<article class="dex-row" data-volume="${p.volume_24h||0}" data-liquidity="${p.liquidity||0}" data-filter="${e((p.base+' '+p.quote+' '+p.chain+' '+p.dex).toLowerCase())}"><div class="dex-identity"><h3><bdi>${e(p.base)} <span class="muted">/</span> ${e(p.quote)}</bdi></h3><p><span class="badge">${e(p.chain)}</span> <bdi class="muted">${e(p.dex)}</bdi></p></div><div class="dex-metric"><span>قیمت USD</span><strong>${money(p.price)}</strong></div><div class="dex-metric"><span>حجم ۲۴ ساعت</span><strong>${money(p.volume_24h,true)}</strong></div><div class="dex-metric"><span>نقدینگی</span><strong>${money(p.liquidity,true)}</strong></div><details class="dex-details" data-pair-index="${index}"><summary>تحلیل جفت و نمودار</summary><div class="dex-analysis-body"></div><button class="dex-chart-toggle" data-dex-chart aria-expanded="false">نمایش نمودار شمعی و معاملات</button><div class="dex-chart-host"></div></details></article>`).join('')}</div><p id="dex-empty" class="empty" hidden>جفتی با این جست‌وجو پیدا نشد.</p></section>`;
 }else{
 content=`<p class="hint">داده تکمیلی انگلیسی از CoinPaprika؛ اعضای تیم ممکن است توسعه‌دهنده یا مشارکت‌کننده باشند و الزاماً بنیان‌گذار نیستند.</p><div class="data-card-grid">${data.items.map(p=>`<article class="panel"><h2>${e(p.name)} <bdi>${e(p.symbol)}</bdi></h2><details><summary>شرح پروژه به زبان منبع</summary><p dir="auto">${e(p.description||'توضیح موجود نیست')}</p></details><h3>تیم ثبت‌شده در منبع</h3><ul>${p.team.map(t=>`<li dir="auto">${e(t.name)} — ${e(t.position)}</li>`).join('')||'<li>اطلاعات موجود نیست</li>'}</ul>${link(p.source_url,'صفحه پروژه و منابع')}</article>`).join('')}</div>`;
 }
 main.innerHTML=`<div class="heading"><div><h1>کاوش داده‌های کریپتو</h1><p class="subtitle">احساسات بازار، دیفای، معاملات آن‌چین و اطلاعات پروژه‌ها</p></div></div><nav class="explore-tabs" aria-label="داده‌های کاوش">${Object.entries(tabs).map(([k,label])=>`<a class="action-link ${selected===k?'primary':''}" href="#explore?tab=${k}" ${selected===k?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${data.fetched_at?`<p class="muted">دریافت: ${e(date(data.fetched_at))}${data.freshness==='stale'?' · داده قدیمی':data._offline?' · نسخه آفلاین':''}</p>`:''}${data.source_url?`<p>${link(data.source_url,selected==='projects'?'Powered by CoinPaprika':'منبع: '+data.source)}</p>`:''}<div class="explore-content">${content}</div>`;
 const ctx={client,current,e,num,money,date,link};const protocol=main.querySelector('#protocol-analytics');if(protocol&&client.mode!=='demo')await renderProtocolBrowser(protocol,ctx);if(!current())return;main.querySelectorAll('[data-pair-index]').forEach(details=>{const p=data.items[Number(details.dataset.pairIndex)],body=details.querySelector('.dex-analysis-body');details.addEventListener('toggle',()=>{if(details.open&&!body.innerHTML)body.innerHTML=dexDetails(p,ctx);});details.querySelector('[data-dex-chart]').addEventListener('click',event=>{const button=event.currentTarget,host=details.querySelector('.dex-chart-host');if(host.innerHTML){host.innerHTML='';button.textContent='نمایش نمودار شمعی و معاملات';button.setAttribute('aria-expanded','false');return;}const url=dexEmbedURL(p,document.documentElement.dataset.theme);if(!url){host.innerHTML='<p class=error>نشانی نمودار معتبر نیست؛ از لینک منبع استفاده کنید.</p>';return;}host.innerHTML=`<p class=muted>نمودار و جدول انگلیسی از DEX Screener؛ در صورت عدم بارگذاری، لینک منبع را باز کنید.</p><iframe class="dex-embed" title="${e(p.base)} / ${e(p.quote)} — DEX Screener" src="${e(url)}" loading="lazy" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-popups"></iframe>`;button.textContent='بستن نمودار';button.setAttribute('aria-expanded','true');});body.addEventListener('click',event=>{const button=event.target.closest('[data-dex-period]');if(button){body.innerHTML=dexDetails(p,ctx,button.dataset.dexPeriod);body.querySelector(`[data-dex-period="${button.dataset.dexPeriod}"]`)?.focus();}});});
 const input=main.querySelector('#explore-search');const filter=()=>{const q=input?.value.trim().toLowerCase()||'';let count=0;main.querySelectorAll('[data-filter]').forEach(row=>{row.hidden=!row.dataset.filter.includes(q);if(!row.hidden)count++;});const output=main.querySelector('#dex-count');if(output)output.textContent=`${num(count)} جفت قابل نمایش`;const empty=main.querySelector('#dex-empty');if(empty)empty.hidden=count>0;};if(input){input.addEventListener('input',filter);filter();}const sort=main.querySelector('#dex-sort');if(sort)sort.addEventListener('change',()=>{const field=sort.value==='liquidity'?'liquidity':'volume';const list=main.querySelector('.dex-list');[...list.children].sort((a,b)=>Number(b.dataset[field])-Number(a.dataset[field])).forEach(row=>list.append(row));});
}

