name: nabz_coin
description: Persian cryptocurrency market and news client.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.2
  dio: ^5.11.1
  fl_chart: ^1.2.0
  shared_preferences: ^2.5.5
  shamsi_date: ^1.1.1
  url_launcher: ^6.3.3
  share_plus: ^13.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
