import test from 'node:test';import assert from 'node:assert/strict';
import {demoMarket,demoChart,selectCoins,usd,date,relative,escapeHTML,safeURL,chartPath,DataClient,APIError} from '../data.js';
test('Tehran calendar time and relative publication date are explicit',()=>{assert.ok(date('2026-10-05T08:00:00Z').includes('۱۱:۳۰'));assert.ok(relative('2026-10-05T07:00:00Z',Date.parse('2026-10-05T08:00:00Z')).includes('پیش'));assert.equal(date('bad'),'زمان نامشخص');});
test('100 demo coins with stable IDs; search, sort and watch scope',()=>{const m=demoMarket();assert.equal(m.items.length,100);assert.equal(new Set(m.items.map(c=>c.id)).size,100);assert.equal(selectCoins(m.items,{query:'بیت‌کوین'})[0].id,1);assert.equal(selectCoins(m.items,{watch:[1027]}).length,1);assert.ok(selectCoins(m.items,{sort:'gainers'})[0].change_24h>0);assert.ok(selectCoins(m.items,{sort:'losers'})[0].change_24h<0);});
test('tiny USD remains nonzero and source text cannot create markup',()=>{assert.notEqual(usd(1.23e-11,false),usd(0,false));assert.equal(escapeHTML('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.equal(safeURL('javascript:alert(1)'),null);assert.equal(safeURL('https://user:pass@example.com'),null);});
test('charts use chronological time and finite coordinates for constant series',()=>{const points=demoChart(demoMarket().items[0],'7d').points;assert.ok(Date.parse(points[0].time)<Date.parse(points.at(-1).time));assert.equal(chartPath([{time:'2026-01-01',price:1}]),'M450.00,125.00');assert.ok(!chartPath(points).includes('NaN'));assert.throws(()=>demoChart(demoMarket().items[0],'unknown'));});
test('live offline cache survives restart; 403 and demo cannot fall back',async()=>{const entries=new Map(),storage={setItem:(k,v)=>entries.set(k,v),getItem:k=>entries.get(k)};let state='online';const fetcher=async()=>{if(state==='offline')throw TypeError('offline');return {ok:state!=='403',status:403,json:async()=>({mode:state==='demo'?'demo':'live',items:[]})};};const client=()=>new DataClient({mode:'live',storage,fetcher});await client().get('/api/v1/market');state='offline';assert.equal((await client().get('/api/v1/market'))._offline,true);state='403';await assert.rejects(client().get('/api/v1/market'),e=>e instanceof APIError&&e.status===403);state='demo';await assert.rejects(client().get('/api/v1/market'),e=>e.status===409);});
test('aborted request and cache from another origin cannot be substituted',async()=>{const entries=new Map(),storage={setItem:(k,v)=>entries.set(k,v),getItem:k=>entries.get(k)};await new DataClient({mode:'live',namespace:'one',storage,fetcher:async()=>({ok:true,json:async()=>({mode:'live'})})}).get('/api/v1/market');await assert.rejects(new DataClient({mode:'live',namespace:'two',storage,fetcher:async()=>{throw Error('offline');}}).get('/api/v1/market'));const error=Error('cancelled');error.name='AbortError';await assert.rejects(new DataClient({mode:'live',namespace:'one',storage,fetcher:async()=>{throw error;}}).get('/api/v1/market'),{name:'AbortError'});});
test('browser fetch receives its required global receiver',async()=>{const original=globalThis.fetch;globalThis.fetch=async function(){assert.equal(this,globalThis);return {ok:true,json:async()=>({mode:'live',items:[]})};};try{assert.equal((await new DataClient({mode:'live',storage:null}).get('/api/v1/market')).mode,'live');}finally{globalThis.fetch=original;}});
